services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DFAU\ToujouApi\:
    resource: '../Classes/*'

  DFAU\ToujouApi\Utility\AbsoluteFileUrBuilder:
    public: true

  DFAU\ToujouApi\Database\Query\Restriction\LanguageRestriction:
    public: true

  DFAU\ToujouApi\Database\Query\Restriction\SiteRestriction:
    public: true
